### ISSUE TITLE
Documented build targed azure-ref not existing

### ISSUE THREAD

**Issue by tobias-hd** [SAP-samples/sap-iot-hyperscaler-azure-integration-ref#4]
In the README you write:
```
Run Maven build locally (mvn clean install) and get the zip file from azure-iot-integration-ref/azure-ref/target folder
```
I assume that the base folder should rather be `sap-iot-hyperscaler-azure-integration-ref`, not `azure-iot-integration-ref`.
However, the target `azure-ref` does not exist, after running a `mvn clean install`. The individual zip files have to be taken separately from the 3 sub-modules.

**Comment by pjdillon** [comment]
Hi Tobias,

Thanks for brnging this to our attention. We have provided a fix for this and you should be able to pull the latest changes.

Prerna
