### ISSUE TITLE
Test failed IoTSPayloadMapperTest

### ISSUE THREAD

**Issue by mths1** [SAP-samples/sap-iot-hyperscaler-azure-integration-ref#6]
To reproduce:

git clone
mvn clean
mvn install

// Expected: A successfull build with all tests passed
// Act: Test fails

java -v
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.671 s <<< FAILURE! - in com.sap.iot.azure.ref.ingestion.device.mapping.IoTSPayloadMapperTest
[ERROR] testAbstractRawMessagesWithLongTimeFormat(com.sap.iot.azure.ref.ingestion.device.mapping.IoTSPayloadMapperTest)  Time elapsed: 0.477 s  <<< FAILURE!
java.lang.AssertionError: expected:<2021-01-20T15:19:45.434119Z> but was:<2021-01-20T15:19:45.434Z>
        at com.sap.iot.azure.ref.ingestion.device.mapping.IoTSPayloadMapperTest.assertIoTSDeviceMeasure(IoTSPayloadMapperTest.java:126)
        at com.sap.iot.azure.ref.ingestion.device.mapping.IoTSPayloadMapperTest.testAbstractRawMessagesWithLongTimeFormat(IoTSPayloadMapperTest.java:66)

**Comment by pjdillon** [comment]
Thank you for bringing this to our attention. This issue has been fixed in our latest release.

Note: We officially support jdk version 8 as mentioned in our documentation however in this case since fix was minor we have addressed the issue. Thank you!
